site_name: "Reautomatizacion Aura 1000"
use_directory_urls: false

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.expand

nav:
  - Inicio: index.md
  - Estructura de Carpetas: arquitectura/carpetas.md
  - /config (Señales):
    - Indice: config/index.md
    - Digitales (digital_signals.py): config/digital_signals.md
    - Analogicas (analog_signals.py): config/analog_signals.md
  - /drivers:
    - Índice: drivers/index.md
    - Analogico (analog_driver.py): drivers/analogico.md
    - Digital (dio_driver.py): drivers/digital.md
  - /gui:
    - Índice: gui/index.md
    - Interfaz diseñada en PyQt5 (pyqt_gui.py): gui/pyqt_gui.md
    - Ventana de arranque y ejecucion de programa (main_window.py): gui/main_window.md
  - /services:
    - Índice: services/index.md
    - Clase con metodos de alto nivel para control de hardware (hardware.py): services/hardware.md
    - Enumeracion de estados de maquina de estados (system_state.py): services/system_state.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            filters: 
              - "!^_" # Muestra todo lo que no empiece con guión bajo (es decir, variables públicas)

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details      